"""add categorie produit photo tables

Revision ID: 6225571fe9c4
Revises: f8b872fa1572
Create Date: 2026-09-22 17:45:41.101229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6225571fe9c4'
down_revision: Union[str, None] = 'f8b872fa1572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorie_id'), 'categorie', ['id'], unique=False)
    op.create_index(op.f('ix_categorie_slug'), 'categorie', ['slug'], unique=True)
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.Column('disponibilite', sa.Enum('disponible', 'rupture', 'sur_commande', name='disponibilite_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produit_id'), 'produit', ['id'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('principale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_produit_id'), table_name='produit')
    op.drop_table('produit')
    op.drop_index(op.f('ix_categorie_slug'), table_name='categorie')
    op.drop_index(op.f('ix_categorie_id'), table_name='categorie')
    op.drop_table('categorie')
    # ### end Alembic commands ###
    # drop_table leaves Postgres enum types behind; without this, re-running
    # upgrade fails with "type disponibilite_enum already exists".
    sa.Enum(name='disponibilite_enum').drop(op.get_bind(), checkfirst=True)
